apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: customerservices.hubc.app
spec:
  scope: Namespaced
  group: hubc.app
  names:
    kind: CustomerService
    singular: customerservice
    plural: customerservices
    shortNames:
      - c-s
      - c-ss
      - c-svc
      - c-svcs
      - c-service
      - c-services
  versions:
    - name: v1
      served: true
      storage: true
      additionalPrinterColumns:
        - name: Service
          type: string
          jsonPath: .spec.service
        - name: Age
          type: date
          jsonPath: .metadata.creationTimestamp
      schema:
        openAPIV3Schema:
          type: object
          required:
            - spec
          properties:
            spec:
              type: object
              required:
                - service
              properties:
                service:
                  type: string
                  enum:
                    # This here lists all possible service types:
                    - hello-world
                    - goodbye-world
                options:
                  type: object
                  # This defines the options object as a string-to-string map
                  additionalProperties:
                    type: string
      subresources:
        status: {}
