apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: customerconfigurations.hubc.app
spec:
  scope: Namespaced
  group: hubc.app
  names:
    kind: CustomerConfiguration
    singular: customerconfiguration
    plural: customerconfigurations
    shortNames:
      - c-c
      - c-cs
      - c-config
      - c-configs
      - c-configuration
      - c-configurations
  versions:
    - name: v1
      served: true
      storage: true
      additionalPrinterColumns:
        - name: Company name
          type: string
          jsonPath: .spec.companyName
        - name: Age
          type: date
          jsonPath: .metadata.creationTimestamp
      schema:
        openAPIV3Schema:
          type: object
          required:
            - spec
          properties:
            spec:
              type: object
              required:
                - companyName
              properties:
                companyName:
                  type: string
                logo:
                  type: string
                  format: url
              # Allow properties outside the current schema to be added
              additionalProperties: true
